// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pepela.Data;

#nullable disable

namespace Pepela.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240922130047_AssociationSeats")]
    partial class AssociationSeats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pepela.Data.ReservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant?>("CancelledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("ConfirmedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("MadeOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagementToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PubQuizSeats")
                        .HasColumnType("integer");

                    b.Property<string>("PubQuizTeamName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Seats")
                        .HasColumnType("integer");

                    b.Property<bool>("SleepOver")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Pepela.Data.ReservationTimeSlotAssociation", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("integer");

                    b.Property<int>("TakenTimeSlotSeats")
                        .HasColumnType("integer");

                    b.HasKey("ReservationId", "TimeSlotId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("ReservationTimeSlotAssociation");
                });

            modelBuilder.Entity("Pepela.Data.SlottedActivityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Pepela.Data.TimeSlotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<bool>("AlwaysConsumeOnePerReservation")
                        .HasColumnType("boolean");

                    b.Property<Instant>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Instant>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("Pepela.Data.ReservationTimeSlotAssociation", b =>
                {
                    b.HasOne("Pepela.Data.ReservationEntity", "Reservation")
                        .WithMany("TimeSlotAssociations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pepela.Data.TimeSlotEntity", "TimeSlot")
                        .WithMany("ReservationAssociations")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("Pepela.Data.TimeSlotEntity", b =>
                {
                    b.HasOne("Pepela.Data.SlottedActivityEntity", "Activity")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Pepela.Data.ReservationEntity", b =>
                {
                    b.Navigation("TimeSlotAssociations");
                });

            modelBuilder.Entity("Pepela.Data.SlottedActivityEntity", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("Pepela.Data.TimeSlotEntity", b =>
                {
                    b.Navigation("ReservationAssociations");
                });
#pragma warning restore 612, 618
        }
    }
}
